export interface CategoryConfig {
  services: string[];
  priceHint: string;
  priceSuggestions: string[];
  jobTypes: ("Home Service" | "Shop Visit" | "Online" | "Home Collection")[];
  serviceLabelPlural: string;
  keywords: string[];
}

export const JOB_TYPE_ICONS: Record<string, string> = {
  "Home Service": "🏠",
  "Shop Visit": "🏪",
  "Online": "💻",
  "Home Collection": "🧪",
};

export const CATEGORY_CONFIG: Record<string, CategoryConfig> = {
  "Plumber": {
    services: ["Leak fixing", "Pipe installation", "Bathroom fitting", "Tank cleaning", "Waterproofing", "Drain unblocking", "Geyser installation"],
    priceHint: "₹300–₹1500 per visit",
    priceSuggestions: ["₹200–₹500", "₹500–₹1500", "₹1500+"],
    jobTypes: ["Home Service"],
    serviceLabelPlural: "Specializations",
    keywords: ["plumber near me", "pipe repair", "bathroom fitting", "leak fixing"],
  },
  "Electrician": {
    services: ["Wiring", "Panel upgrade", "Lighting installation", "Fan / AC fitting", "CCTV wiring", "Inverter installation", "Short circuit repair"],
    priceHint: "₹200–₹2000 per job",
    priceSuggestions: ["₹200–₹500", "₹500–₹2000", "₹2000+"],
    jobTypes: ["Home Service"],
    serviceLabelPlural: "Services Offered",
    keywords: ["electrician near me", "wiring repair", "electrical work"],
  },
  "Salon / Barbershop": {
    services: ["Haircut", "Beard styling", "Hair coloring", "Facial", "Waxing", "Blowdry", "Keratin treatment", "Manicure", "Pedicure"],
    priceHint: "₹150–₹2000 per service",
    priceSuggestions: ["₹100–₹500", "₹500–₹2000", "₹2000+"],
    jobTypes: ["Shop Visit", "Home Service"],
    serviceLabelPlural: "Services Offered",
    keywords: ["salon near me", "haircut price", "beauty parlour", "barbershop"],
  },
  "AC Repair": {
    services: ["AC servicing", "Gas refill", "Installation", "PCB repair", "Cooling issue fix", "Remote repair", "Deep cleaning"],
    priceHint: "₹400–₹2000 per visit",
    priceSuggestions: ["₹300–₹700", "₹700–₹2000", "₹2000+"],
    jobTypes: ["Home Service"],
    serviceLabelPlural: "Services Offered",
    keywords: ["AC repair near me", "AC service", "gas refill", "air conditioner repair"],
  },
  "Gym / Fitness": {
    services: ["Weight training", "Zumba", "Yoga", "CrossFit", "Personal training", "Cardio", "Kickboxing", "Diet consultation"],
    priceHint: "₹1000–₹3000 per month",
    priceSuggestions: ["₹500–₹1500/mo", "₹1500–₹3000/mo", "₹3000+/mo"],
    jobTypes: ["Shop Visit", "Online"],
    serviceLabelPlural: "Facilities / Classes",
    keywords: ["gym near me", "fitness center", "yoga classes", "personal trainer"],
  },
  "Dentist": {
    services: ["Dental cleaning", "Tooth extraction", "Root canal", "Braces", "Teeth whitening", "Implants", "Filling", "X-ray"],
    priceHint: "₹300–₹15000 per procedure",
    priceSuggestions: ["₹300–₹1000", "₹1000–₹5000", "₹5000+"],
    jobTypes: ["Shop Visit"],
    serviceLabelPlural: "Dental Services",
    keywords: ["dentist near me", "dental clinic", "teeth cleaning", "braces"],
  },
  "Car Mechanic": {
    services: ["Engine repair", "Denting & painting", "Oil change", "Brake repair", "AC repair", "Wheel alignment", "Battery replacement"],
    priceHint: "₹500–₹10000 per job",
    priceSuggestions: ["₹500–₹2000", "₹2000–₹10000", "₹10000+"],
    jobTypes: ["Shop Visit", "Home Service"],
    serviceLabelPlural: "Specializations",
    keywords: ["car mechanic near me", "car service", "car repair", "auto workshop"],
  },
  "Bike Repair": {
    services: ["Engine repair", "Tyre change", "Chain replacement", "Brake adjustment", "Oil change", "Battery", "Full servicing"],
    priceHint: "₹200–₹3000 per job",
    priceSuggestions: ["₹200–₹500", "₹500–₹3000", "₹3000+"],
    jobTypes: ["Shop Visit", "Home Service"],
    serviceLabelPlural: "Specializations",
    keywords: ["bike mechanic near me", "motorcycle repair", "two wheeler service"],
  },
  "Home Cleaning": {
    services: ["Deep cleaning", "Kitchen cleaning", "Bathroom cleaning", "Sofa cleaning", "Carpet cleaning", "Post-construction cleaning", "Regular cleaning"],
    priceHint: "₹1000–₹5000 per session",
    priceSuggestions: ["₹500–₹1500", "₹1500–₹5000", "₹5000+"],
    jobTypes: ["Home Service"],
    serviceLabelPlural: "Services Offered",
    keywords: ["home cleaning near me", "deep cleaning service", "sofa cleaning", "maid service"],
  },
  "Painter": {
    services: ["Interior painting", "Exterior painting", "Texture work", "Waterproofing", "Wall putty", "Wood painting", "Commercial painting"],
    priceHint: "₹12–₹25 per sq ft",
    priceSuggestions: ["₹10–₹15/sqft", "₹15–₹25/sqft", "₹25+/sqft"],
    jobTypes: ["Home Service"],
    serviceLabelPlural: "Services Offered",
    keywords: ["painter near me", "house painting", "wall painting", "interior painter"],
  },
  "Carpenter": {
    services: ["Furniture repair", "Modular kitchen", "Wardrobe", "Door fitting", "False ceiling", "Bed assembly", "Custom furniture"],
    priceHint: "₹500–₹15000 per job",
    priceSuggestions: ["₹500–₹2000", "₹2000–₹15000", "₹15000+"],
    jobTypes: ["Home Service"],
    serviceLabelPlural: "Specializations",
    keywords: ["carpenter near me", "furniture repair", "modular kitchen", "woodwork"],
  },
  "RO / Water Filter": {
    services: ["RO installation", "Filter change", "RO repair", "AMC", "Tank cleaning", "Water testing", "UV filter service"],
    priceHint: "₹300–₹2000 per visit",
    priceSuggestions: ["₹300–₹700", "₹700–₹2000", "AMC plans"],
    jobTypes: ["Home Service"],
    serviceLabelPlural: "Services Offered",
    keywords: ["RO repair near me", "water purifier service", "RO installation"],
  },
  "Real Estate": {
    services: ["Buy / Sell property", "Rental assistance", "Property valuation", "Legal documentation", "Site visits", "Investment advice", "Commercial leasing"],
    priceHint: "1–2% brokerage",
    priceSuggestions: ["1% commission", "2% commission", "Fixed fee"],
    jobTypes: ["Home Service", "Online", "Shop Visit"],
    serviceLabelPlural: "Services Offered",
    keywords: ["real estate agent near me", "property dealer", "flat for rent", "property valuation"],
  },
  "Interior Designer": {
    services: ["Home interior design", "Office design", "Modular kitchen", "3D visualization", "False ceiling", "Furniture selection", "Renovation planning"],
    priceHint: "₹50–₹200 per sq ft",
    priceSuggestions: ["₹50–₹100/sqft", "₹100–₹200/sqft", "₹200+/sqft"],
    jobTypes: ["Home Service", "Online"],
    serviceLabelPlural: "Services Offered",
    keywords: ["interior designer near me", "home decorator", "interior design cost", "modular kitchen"],
  },
  "CCTV Installation": {
    services: ["CCTV installation", "DVR/NVR setup", "Camera maintenance", "Remote monitoring setup", "Video doorbell", "Access control", "Wiring"],
    priceHint: "₹2000–₹20000 per setup",
    priceSuggestions: ["₹2000–₹5000", "₹5000–₹15000", "₹15000+"],
    jobTypes: ["Home Service"],
    serviceLabelPlural: "Services Offered",
    keywords: ["CCTV installation near me", "security camera", "DVR setup", "surveillance system"],
  },
  "Solar Panel": {
    services: ["Solar installation", "Inverter setup", "Panel cleaning", "AMC", "Grid-tie system", "Off-grid system", "Solar water heater"],
    priceHint: "₹40000–₹200000 per system",
    priceSuggestions: ["₹40k–₹80k", "₹80k–₹150k", "₹150k+"],
    jobTypes: ["Home Service"],
    serviceLabelPlural: "Services Offered",
    keywords: ["solar panel installation", "solar energy", "solar system cost", "solar inverter"],
  },
  "Laptop Repair": {
    services: ["Screen replacement", "Keyboard repair", "Data recovery", "OS installation", "Virus removal", "RAM/SSD upgrade", "Motherboard repair"],
    priceHint: "₹300–₹8000 per repair",
    priceSuggestions: ["₹300–₹1000", "₹1000–₹5000", "₹5000+"],
    jobTypes: ["Shop Visit", "Home Service"],
    serviceLabelPlural: "Services Offered",
    keywords: ["laptop repair near me", "computer repair", "screen replacement", "data recovery"],
  },
  "Tutor": {
    services: ["Mathematics", "Science", "English", "Hindi", "IIT-JEE prep", "NEET prep", "Board exam coaching", "Coding", "Spoken English"],
    priceHint: "₹300–₹1000 per hour",
    priceSuggestions: ["₹200–₹500/hr", "₹500–₹1000/hr", "₹1000+/hr"],
    jobTypes: ["Home Service", "Online", "Shop Visit"],
    serviceLabelPlural: "Subjects / Levels",
    keywords: ["tutor near me", "home tuition", "private teacher", "IIT JEE coaching"],
  },
  "Photographer": {
    services: ["Wedding photography", "Portrait session", "Product photography", "Event coverage", "Pre-wedding shoot", "Baby shoot", "Real estate shoot"],
    priceHint: "₹5000–₹50000 per event",
    priceSuggestions: ["₹3000–₹10000", "₹10000–₹50000", "₹50000+"],
    jobTypes: ["Home Service", "Online"],
    serviceLabelPlural: "Specializations",
    keywords: ["photographer near me", "wedding photographer", "portrait photography", "event photographer"],
  },
  "Makeup Artist": {
    services: ["Bridal makeup", "Party makeup", "HD makeup", "Airbrush makeup", "Hair styling", "Mehendi", "Engagement look"],
    priceHint: "₹1500–₹15000 per look",
    priceSuggestions: ["₹1500–₹5000", "₹5000–₹15000", "₹15000+"],
    jobTypes: ["Home Service", "Shop Visit"],
    serviceLabelPlural: "Services Offered",
    keywords: ["makeup artist near me", "bridal makeup", "party makeup", "HD makeup"],
  },
  "Event Planner": {
    services: ["Wedding planning", "Birthday party", "Corporate event", "Decoration", "Catering coordination", "DJ & sound", "Photography coordination"],
    priceHint: "₹20000–₹500000 per event",
    priceSuggestions: ["₹10k–₹50k", "₹50k–₹200k", "₹200k+"],
    jobTypes: ["Home Service", "Online"],
    serviceLabelPlural: "Event Types",
    keywords: ["event planner near me", "wedding planner", "birthday party organizer", "event management"],
  },
  "Spa / Wellness": {
    services: ["Body massage", "Facial", "Body wrap", "Aromatherapy", "Head massage", "Hot stone therapy", "Couple spa", "Meditation session"],
    priceHint: "₹800–₹5000 per session",
    priceSuggestions: ["₹500–₹1500", "₹1500–₹5000", "₹5000+"],
    jobTypes: ["Shop Visit", "Home Service"],
    serviceLabelPlural: "Treatments Offered",
    keywords: ["spa near me", "massage centre", "body massage", "wellness spa"],
  },
  "Doctor / Clinic": {
    services: ["General OPD", "Diabetes care", "Child health", "Women's health", "Heart checkup", "Blood test", "Online consultation"],
    priceHint: "₹200–₹800 per visit",
    priceSuggestions: ["₹200–₹400", "₹400–₹800", "₹800+"],
    jobTypes: ["Shop Visit", "Online"],
    serviceLabelPlural: "Specialization / OPD",
    keywords: ["doctor near me", "clinic near me", "general physician", "OPD timings"],
  },
  "Tailor": {
    services: ["Blouse stitching", "Suit stitching", "Alterations", "Wedding wear", "School uniform", "Kurta / Sherwani", "Lehenga"],
    priceHint: "₹200–₹5000 per piece",
    priceSuggestions: ["₹200–₹500", "₹500–₹2000", "₹2000+"],
    jobTypes: ["Shop Visit", "Home Service"],
    serviceLabelPlural: "Tailoring Speciality",
    keywords: ["tailor near me", "stitching shop", "dress alteration", "blouse stitching"],
  },
  "Lab / Diagnostics": {
    services: ["CBC (Blood count)", "Thyroid test (T3/T4/TSH)", "Blood sugar (FBS/RBS)", "Urine routine", "Lipid profile", "Liver function test", "Kidney function test", "Vitamin D / B12", "COVID RT-PCR", "X-Ray / ECG", "Home sample collection"],
    priceHint: "₹99–₹3000 per test",
    priceSuggestions: ["₹99–₹500", "₹500–₹1500", "₹1500+"],
    jobTypes: ["Shop Visit", "Home Collection"],
    serviceLabelPlural: "Tests Available",
    keywords: ["lab near me", "blood test near me", "diagnostic centre", "home sample collection", "pathology lab"],
  },
};
